//go:build browser

// Code generated by torque. DO NOT EDIT.

package layouts

import (
	playwright "github.com/mxschmitt/playwright-go"
	components "github.com/tylermmorton/torque/.www/docsite/components"
)

type DocsLayoutPageObject struct {
	locator playwright.Locator
}

func NewDocsLayoutPageObject(page playwright.Page) *DocsLayoutPageObject {
	return &DocsLayoutPageObject{locator: page.Locator("html")}
}

func NewDocsLayoutPageObjectFromLocator(locator playwright.Locator) *DocsLayoutPageObject {
	return &DocsLayoutPageObject{locator: locator}
}

func (p *DocsLayoutPageObject) Stars() *components.StargazersPageObject {
	return components.NewStargazersPageObjectFromLocator(p.locator.Locator("[data-test-id='github-stars']"))
}

func (p *DocsLayoutPageObject) Search() *components.SearchDialogPageObject {
	return components.NewSearchDialogPageObjectFromLocator(p.locator.Locator("[data-test-id='search-dialog']"))
}
