// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package services

import (
	"context"
	"sync"

	"github.com/tylermmorton/torque/.www/docsite/services"
	"github.com/tylermmorton/torque/.www/docsite/services/model"
)

// Ensure that MockDocumentService does implement services.DocumentService.
// If this is not the case, regenerate this file with mockery.
var _ services.DocumentService = &MockDocumentService{}

// MockDocumentService is a mock implementation of services.DocumentService.
//
//	func TestSomethingThatUsesDocumentService(t *testing.T) {
//
//		// make and configure a mocked services.DocumentService
//		mockedDocumentService := &MockDocumentService{
//			GetByNameFunc: func(ctx context.Context, documentName string) (*model.Document, error) {
//				panic("mock out the GetByName method")
//			},
//		}
//
//		// use mockedDocumentService in code that requires services.DocumentService
//		// and then make assertions.
//
//	}
type MockDocumentService struct {
	// GetByNameFunc mocks the GetByName method.
	GetByNameFunc func(ctx context.Context, documentName string) (*model.Document, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetByName holds details about calls to the GetByName method.
		GetByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocumentName is the documentName argument value.
			DocumentName string
		}
	}
	lockGetByName sync.RWMutex
}

// GetByName calls GetByNameFunc.
func (mock *MockDocumentService) GetByName(ctx context.Context, documentName string) (*model.Document, error) {
	if mock.GetByNameFunc == nil {
		panic("MockDocumentService.GetByNameFunc: method is nil but DocumentService.GetByName was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		DocumentName string
	}{
		Ctx:          ctx,
		DocumentName: documentName,
	}
	mock.lockGetByName.Lock()
	mock.calls.GetByName = append(mock.calls.GetByName, callInfo)
	mock.lockGetByName.Unlock()
	return mock.GetByNameFunc(ctx, documentName)
}

// GetByNameCalls gets all the calls that were made to GetByName.
// Check the length with:
//
//	len(mockedDocumentService.GetByNameCalls())
func (mock *MockDocumentService) GetByNameCalls() []struct {
	Ctx          context.Context
	DocumentName string
} {
	var calls []struct {
		Ctx          context.Context
		DocumentName string
	}
	mock.lockGetByName.RLock()
	calls = mock.calls.GetByName
	mock.lockGetByName.RUnlock()
	return calls
}
