// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package services

import (
	"context"
	"sync"

	"github.com/tylermmorton/torque/.www/docsite/services"
)

// Ensure that MockGitHubService does implement services.GitHubService.
// If this is not the case, regenerate this file with mockery.
var _ services.GitHubService = &MockGitHubService{}

// MockGitHubService is a mock implementation of services.GitHubService.
//
//	func TestSomethingThatUsesGitHubService(t *testing.T) {
//
//		// make and configure a mocked services.GitHubService
//		mockedGitHubService := &MockGitHubService{
//			GetStarsFunc: func(ctx context.Context, repoURL string) (int, error) {
//				panic("mock out the GetStars method")
//			},
//		}
//
//		// use mockedGitHubService in code that requires services.GitHubService
//		// and then make assertions.
//
//	}
type MockGitHubService struct {
	// GetStarsFunc mocks the GetStars method.
	GetStarsFunc func(ctx context.Context, repoURL string) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetStars holds details about calls to the GetStars method.
		GetStars []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoURL is the repoURL argument value.
			RepoURL string
		}
	}
	lockGetStars sync.RWMutex
}

// GetStars calls GetStarsFunc.
func (mock *MockGitHubService) GetStars(ctx context.Context, repoURL string) (int, error) {
	if mock.GetStarsFunc == nil {
		panic("MockGitHubService.GetStarsFunc: method is nil but GitHubService.GetStars was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		RepoURL string
	}{
		Ctx:     ctx,
		RepoURL: repoURL,
	}
	mock.lockGetStars.Lock()
	mock.calls.GetStars = append(mock.calls.GetStars, callInfo)
	mock.lockGetStars.Unlock()
	return mock.GetStarsFunc(ctx, repoURL)
}

// GetStarsCalls gets all the calls that were made to GetStars.
// Check the length with:
//
//	len(mockedGitHubService.GetStarsCalls())
func (mock *MockGitHubService) GetStarsCalls() []struct {
	Ctx     context.Context
	RepoURL string
} {
	var calls []struct {
		Ctx     context.Context
		RepoURL string
	}
	mock.lockGetStars.RLock()
	calls = mock.calls.GetStars
	mock.lockGetStars.RUnlock()
	return calls
}
