//go:build browser

// Code generated by torque. DO NOT EDIT.

package routes

import (
	playwright "github.com/mxschmitt/playwright-go"
	components "github.com/tylermmorton/torque/.www/docsite/components"
	"github.com/tylermmorton/torque/pkg/pageobjects"
)

type DocumentPageObject struct {
	locator playwright.Locator
}

func NewDocumentPageObject(page playwright.Page) *DocumentPageObject {
	return &DocumentPageObject{locator: page.Locator("html")}
}

func NewDocumentPageObjectFromLocator(locator playwright.Locator) *DocumentPageObject {
	return &DocumentPageObject{locator: locator}
}

func (p *DocumentPageObject) DocContent() *pageobjects.Element {
	return pageobjects.NewElement(p.locator.Locator("[data-test-id='doc-content']"))
}

func (p *DocumentPageObject) DocTitle() *pageobjects.Element {
	return pageobjects.NewElement(p.locator.Locator("[data-test-id='doc-title']"))
}

func (p *DocumentPageObject) DocBody() *pageobjects.Element {
	return pageobjects.NewElement(p.locator.Locator("[data-test-id='doc-body']"))
}

func (p *DocumentPageObject) DocPlaceholder() *pageobjects.Element {
	return pageobjects.NewElement(p.locator.Locator("[data-test-id='doc-placeholder']"))
}

func (p *DocumentPageObject) TOC() *components.TableOfContentsPageObject {
	return components.NewTableOfContentsPageObjectFromLocator(p.locator.Locator("[data-test-id='toc']"))
}
