//go:build browser

// Code generated by torque. DO NOT EDIT.

package components

import (
	playwright "github.com/mxschmitt/playwright-go"
	"github.com/tylermmorton/torque/pkg/pageobjects"
)

type StargazersPageObject struct {
	locator playwright.Locator
}

func NewStargazersPageObject(page playwright.Page) *StargazersPageObject {
	return &StargazersPageObject{locator: page.Locator("html")}
}

func NewStargazersPageObjectFromLocator(locator playwright.Locator) *StargazersPageObject {
	return &StargazersPageObject{locator: locator}
}

func (p *StargazersPageObject) StarsContainer() *pageobjects.Element {
	return pageobjects.NewElement(p.locator.Locator("[data-test-id='stars-container']"))
}

func (p *StargazersPageObject) StarCount() *pageobjects.Element {
	return pageobjects.NewElement(p.locator.Locator("[data-test-id='star-count']"))
}
