//go:build browser

// Code generated by torque. DO NOT EDIT.

package components

import (
	playwright "github.com/mxschmitt/playwright-go"
)

type SearchDialogPageObject struct {
	locator playwright.Locator
}

func NewSearchDialogPageObject(page playwright.Page) *SearchDialogPageObject {
	return &SearchDialogPageObject{locator: page.Locator("html")}
}

func NewSearchDialogPageObjectFromLocator(locator playwright.Locator) *SearchDialogPageObject {
	return &SearchDialogPageObject{locator: locator}
}
