//go:build browser

// Code generated by torque. DO NOT EDIT.

package components

import (
	playwright "github.com/mxschmitt/playwright-go"
)

type TableOfContentsPageObject struct {
	locator playwright.Locator
}

func NewTableOfContentsPageObject(page playwright.Page) *TableOfContentsPageObject {
	return &TableOfContentsPageObject{locator: page.Locator("html")}
}

func NewTableOfContentsPageObjectFromLocator(locator playwright.Locator) *TableOfContentsPageObject {
	return &TableOfContentsPageObject{locator: locator}
}
