package torque

import (
	"bytes"
	"fmt"
	"reflect"
	"strings"
	"text/template/parse"

	"golang.org/x/net/html"
)

type TemplateAnalysis struct {
	TemplateProvider TemplateProvider
	// Root is the root node of the html/template's parse.Tree
	Root parse.Node
	// TreeSet is the set of named templates and their parse trees.
	TreeSet map[string]*parse.Tree
	// FuncMap is the map of named functions
	FuncMap FuncMap
	// TypeTree is a tree structure of Go type information through
	// the use of reflection
	TypeTree *ReflectedFieldNode
	// HTMLTree is the root html node generated by html.Parse
	HTMLTree *html.Node
	// Results of any custom analyzers
	Results []TemplateAnalyzerResult
	// Errors reported from any custom analyzers
	Errors []string
	// Warnings reported from any custom analyzers
	Warnings []string
}

func (t *TemplateAnalysis) AddError(node parse.Node, errorText string) {
	t.Errors = append(t.Errors, fmt.Sprintf("%v, %s", node.Position(), errorText))
}

func (t *TemplateAnalysis) AddWarning(node parse.Node, warningText string) {
	t.Warnings = append(t.Warnings, fmt.Sprintf("%v, %s", node.Position(), warningText))
}

// IsDefinedTemplate returns true if the given template name is defined in the
// analysis target via {{define}}, or defined by any of its embedded templates.
func (t *TemplateAnalysis) IsDefinedTemplate(name string) bool {
	if name == "outlet" {
		return true
	}

	_, ok := t.TreeSet[name]
	return ok
}

type TemplateAnalyzerResult = any

type TemplateAnalyzer func(analysis *TemplateAnalysis) (TemplateAnalyzerResult, error)

type AnalyzeTemplateOption func(*analyzeTemplateOptions)

func AnalyzeTemplateOptionAnalyzers(analyzers ...TemplateAnalyzer) AnalyzeTemplateOption {
	return func(opts *analyzeTemplateOptions) {
		opts.Analyzers = append(opts.Analyzers, analyzers...)
	}
}

func analyzeTemplateOptionCompiler(compilerOpts *templateCompilerOptions) AnalyzeTemplateOption {
	return func(analyzeOptions *analyzeTemplateOptions) {
		analyzeOptions.compilerOptions = compilerOpts
	}
}

func AnalyzeTemplateOptionCompiler(opts ...TemplateCompilerOption) AnalyzeTemplateOption {
	return func(analyzeOptions *analyzeTemplateOptions) {
		for _, opt := range opts {
			opt(analyzeOptions.compilerOptions)
		}
	}
}

type analyzeTemplateOptions struct {
	compilerOptions *templateCompilerOptions
	Analyzers       []TemplateAnalyzer
}

func AnalyzeTemplate(tp TemplateProvider, opts ...AnalyzeTemplateOption) (*TemplateAnalysis, error) {
	var err error

	analyzeOptions := &analyzeTemplateOptions{
		compilerOptions: &templateCompilerOptions{
			LeftDelim:  "{{",
			RightDelim: "}}",
			FuncMap:    make(FuncMap),
		},
	}
	for _, opt := range opts {
		opt(analyzeOptions)
	}

	analysis := &TemplateAnalysis{
		TemplateProvider: tp,
		TreeSet:          make(map[string]*parse.Tree),
		FuncMap:          analyzeOptions.compilerOptions.FuncMap,
		Results:          make([]TemplateAnalyzerResult, 0),
		Errors:           make([]string, 0),
		Warnings:         make([]string, 0),
	}

	// Detect all defined FuncMaps
	err = recurseFieldsImplementing[FuncMapProvider](tp, func(val FuncMapProvider, field reflect.StructField) error {
		for key, value := range val.FuncMap() {
			analysis.FuncMap[key] = value
		}
		return nil
	})
	if err != nil {
		return nil, err
	}

	// Detect all defined templates and parse trees
	err = recurseFieldsImplementing[TemplateProvider](tp, func(tp TemplateProvider, field reflect.StructField) error {
		templateName, ok := field.Tag.Lookup("template")
		if !ok {
			templateName = strings.TrimPrefix(field.Name, "*")
		}

		parser := parse.New(templateName)
		parser.Mode = parse.SkipFuncCheck | parse.ParseComments

		treeSet := make(map[string]*parse.Tree)
		_, err := parser.Parse(
			tp.Template(),
			analyzeOptions.compilerOptions.LeftDelim,
			analyzeOptions.compilerOptions.RightDelim,
			treeSet,
			nil, // func check mode is off
		)
		if err != nil {
			return err
		}

		for k, v := range treeSet {
			analysis.TreeSet[k] = v
		}

		return nil
	})
	if err != nil {
		return nil, err
	}

	analysis.Root = analysis.TreeSet[strings.TrimPrefix(fmt.Sprintf("%T", tp), "*")].Root

	analysis.TypeTree, err = createReflectedFieldTree(tp)
	if err != nil {
		return nil, err
	}

	analysis.HTMLTree, err = html.Parse(bytes.NewBuffer([]byte(tp.Template())))
	if err != nil {
		return nil, fmt.Errorf("failed to parse html: %w", err)
	}

	for _, analyzer := range analyzeOptions.Analyzers {
		result, err := analyzer(analysis)
		if err != nil {
			return nil, fmt.Errorf("failed to execute analyzer %T: %w", analyzer, err)
		}
		analysis.Results = append(analysis.Results, result)
	}

	return analysis, nil
}

// TemplateNodeVisitorFn is a function that visits nodes in a parse.Tree during a
// tree traversal. See TraverseTemplate
type TemplateNodeVisitorFn = func(parse.Node)

// TraverseTemplate is a depth-first traversal utility for all nodes in a parse.Tree --
// used for static analysis of a Go template.
func TraverseTemplate(cur parse.Node, visitors ...TemplateNodeVisitorFn) {
	for _, visitor := range visitors {
		visitor(cur)
	}

	switch node := cur.(type) {
	case *parse.ActionNode:
		if node.Pipe != nil {
			TraverseTemplate(node.Pipe, visitors...)
		}
	case *parse.BoolNode:
	case *parse.BranchNode:
		if node.Pipe != nil {
			TraverseTemplate(node.Pipe, visitors...)
		}
		if node.List != nil {
			TraverseTemplate(node.List, visitors...)
		}
		if node.ElseList != nil {
			TraverseTemplate(node.ElseList, visitors...)
		}
	case *parse.BreakNode:
	case *parse.ChainNode:
	case *parse.CommandNode:
		if node.Args != nil {
			for _, arg := range node.Args {
				TraverseTemplate(arg, visitors...)
			}
		}
	case *parse.CommentNode:
	case *parse.ContinueNode:
	case *parse.DotNode:
	case *parse.FieldNode:
	case *parse.IdentifierNode:
	case *parse.IfNode:
		TraverseTemplate(&node.BranchNode, visitors...)
	case *parse.ListNode:
		if node.Nodes != nil {
			for _, child := range node.Nodes {
				TraverseTemplate(child, visitors...)
			}
		}
	case *parse.NilNode:
	case *parse.NumberNode:
	case *parse.PipeNode:
		if node.Cmds != nil {
			for _, cmd := range node.Cmds {
				TraverseTemplate(cmd, visitors...)
			}
		}
		if node.Decl != nil {
			for _, decl := range node.Decl {
				TraverseTemplate(decl, visitors...)
			}
		}
	case *parse.RangeNode:
		TraverseTemplate(&node.BranchNode, visitors...)
	case *parse.StringNode:
	case *parse.TemplateNode:
		if node.Pipe != nil {
			TraverseTemplate(node.Pipe, visitors...)
		}
	case *parse.TextNode:
	case *parse.VariableNode:
	case *parse.WithNode:
		TraverseTemplate(&node.BranchNode, visitors...)
	}
}
