package pageobjects

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"text/template"
	"unicode"

	"golang.org/x/net/html"

	"github.com/tylermmorton/torque"
)

type Config struct {
	OutputDir string
	Package   string
}

type registration struct {
	typeName string
	provider torque.TemplateProvider
}

type Generator struct {
	cfg           Config
	registrations []registration
}

func NewGenerator(cfg Config) *Generator {
	return &Generator{cfg: cfg}
}

// Generate queues T for controller generation. T must implement torque.TemplateProvider.
func Generate[T torque.TemplateProvider](g *Generator) {
	var zero T
	rv := reflect.ValueOf(&zero).Elem()
	if rv.Kind() == reflect.Ptr {
		rv.Set(reflect.New(rv.Type().Elem()))
	}
	t := reflect.TypeOf(zero)
	typeName := t.Name()
	if t.Kind() == reflect.Ptr {
		typeName = t.Elem().Name()
	}
	g.registrations = append(g.registrations, registration{
		typeName: typeName,
		provider: zero,
	})
}

func (g *Generator) Run() error {
	if err := os.MkdirAll(g.cfg.OutputDir, 0755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	for _, reg := range g.registrations {
		if err := g.generateController(reg); err != nil {
			return fmt.Errorf("generate %s: %w", reg.typeName, err)
		}
	}
	return nil
}

func (g *Generator) generateController(reg registration) error {
	analysis, err := torque.AnalyzeTemplate(reg.provider)
	if err != nil {
		return fmt.Errorf("analyze template: %w", err)
	}

	leaves := collectDataTestIDs(analysis.HTMLTree)
	children := collectChildControllers(analysis.TypeTree)

	data := controllerData{
		Package:          g.cfg.Package,
		TypeName:         reg.typeName,
		LeafElements:     leaves,
		ChildControllers: children,
	}

	var buf bytes.Buffer
	if err := controllerTmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Printf("warning: could not format %sController: %v\nSource:\n%s", reg.typeName, err, buf.String())
		formatted = buf.Bytes()
	}

	filename := filepath.Join(g.cfg.OutputDir, toSnakeCase(reg.typeName)+"_controller.gen.go")
	if err := os.WriteFile(filename, formatted, 0644); err != nil {
		return fmt.Errorf("write file: %w", err)
	}

	log.Printf("generated %s", filename)
	return nil
}

type controllerData struct {
	Package          string
	TypeName         string
	LeafElements     []leafElement
	ChildControllers []childController
}

type leafElement struct {
	MethodName  string
	ElementType string
	TestID      string
}

type childController struct {
	MethodName     string
	ControllerType string
	Selector       string
}

var controllerTmpl = template.Must(template.New("controller").Parse(`//go:build browser

// Code generated by generate-controllers. DO NOT EDIT.

package {{.Package}}

import (
	playwright "github.com/mxschmitt/playwright-go"{{if .LeafElements}}
	"github.com/tylermmorton/torque/pkg/pageobjects"{{end}}
)

type {{.TypeName}}Controller struct {
	locator playwright.Locator
}

func New{{.TypeName}}Controller(page playwright.Page) *{{.TypeName}}Controller {
	return &{{.TypeName}}Controller{locator: page.Locator("html")}
}

func New{{.TypeName}}ControllerFromLocator(locator playwright.Locator) *{{.TypeName}}Controller {
	return &{{.TypeName}}Controller{locator: locator}
}
{{range .LeafElements}}
func (c *{{$.TypeName}}Controller) {{.MethodName}}() *pageobjects.{{.ElementType}} {
	return pageobjects.New{{.ElementType}}(c.locator.Locator("[data-test-id='{{.TestID}}']"))
}
{{end}}{{range .ChildControllers}}
func (c *{{$.TypeName}}Controller) {{.MethodName}}() *{{.ControllerType}}Controller {
	return New{{.ControllerType}}ControllerFromLocator(c.locator.Locator("[data-test-id='{{.Selector}}']"))
}
{{end}}`))

func collectDataTestIDs(node *html.Node) []leafElement {
	var results []leafElement
	var walk func(*html.Node)
	walk = func(n *html.Node) {
		if n.Type == html.ElementNode {
			for _, attr := range n.Attr {
				if attr.Key == "data-test-id" {
					results = append(results, leafElement{
						MethodName:  kebabToPascal(attr.Val),
						ElementType: tagToElementType(n.Data),
						TestID:      attr.Val,
					})
					break
				}
			}
		}
		for c := n.FirstChild; c != nil; c = c.NextSibling {
			walk(c)
		}
	}
	walk(node)
	return results
}

func collectChildControllers(node *torque.ReflectedFieldNode) []childController {
	if node == nil {
		return nil
	}
	var results []childController
	for _, child := range node.Children {
		templateName, ok := child.StructField.Tag.Lookup("template")
		if !ok {
			continue
		}
		fieldType := child.StructField.Type
		if fieldType.Kind() == reflect.Ptr {
			fieldType = fieldType.Elem()
		}
		results = append(results, childController{
			MethodName:     child.StructField.Name,
			ControllerType: fieldType.Name(),
			Selector:       templateName,
		})
	}
	return results
}

func tagToElementType(tag string) string {
	switch tag {
	case "button":
		return "ButtonElement"
	case "input":
		return "InputElement"
	case "a":
		return "AnchorElement"
	default:
		return "Element"
	}
}

func kebabToPascal(s string) string {
	parts := strings.Split(s, "-")
	var b strings.Builder
	for _, p := range parts {
		if len(p) > 0 {
			b.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	return b.String()
}

func toSnakeCase(s string) string {
	var result []rune
	for i, r := range s {
		if unicode.IsUpper(r) && i > 0 {
			result = append(result, '_')
		}
		result = append(result, unicode.ToLower(r))
	}
	return string(result)
}
