package pageobjects_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/tylermmorton/torque/pkg/analysis"
	"github.com/tylermmorton/torque/pkg/pageobjects"
)

func makeManifest(t *testing.T, tmpl string) (*analysis.ProjectManifest, string) {
	t.Helper()
	tmpDir := t.TempDir()
	manifest := &analysis.ProjectManifest{
		Components: map[string]*analysis.Component{
			"example.Foo": {
				TypeName:    "Foo",
				PackageName: "mypkg",
				PackagePath: "example",
				SourceFile:  filepath.Join(tmpDir, "foo.go"),
				Template:    &tmpl,
			},
		},
	}
	return manifest, tmpDir
}

// TestGenerateFromManifest_output_path verifies that the generator writes
// <stem>_browser.gen.go in the same directory as SourceFile.
func TestGenerateFromManifest_output_path(t *testing.T) {
	tmpDir := t.TempDir()
	tmpl := `<div>hello</div>`
	manifest := &analysis.ProjectManifest{
		Components: map[string]*analysis.Component{
			"example.Foo": {
				TypeName:    "Foo",
				PackageName: "mypkg",
				PackagePath: "example",
				SourceFile:  filepath.Join(tmpDir, "foo.go"),
				Template:    &tmpl,
			},
		},
	}

	written, err := pageobjects.GenerateFromManifest(manifest, pageobjects.StaticConfig{Tag: "browser"})
	require.NoError(t, err)
	require.Len(t, written, 1)

	expected := filepath.Join(tmpDir, "foo_browser.gen.go")
	require.Equal(t, expected, written[0])

	_, statErr := os.Stat(expected)
	require.NoError(t, statErr)
}

// TestGenerateFromManifest_header verifies the generated file header and package declaration.
func TestGenerateFromManifest_header(t *testing.T) {
	manifest, tmpDir := makeManifest(t, "<div>hello</div>")
	_, err := pageobjects.GenerateFromManifest(manifest, pageobjects.StaticConfig{Tag: "browser"})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(tmpDir, "foo_browser.gen.go"))
	require.NoError(t, err)
	s := string(content)

	t.Run("has_do_not_edit_comment", func(t *testing.T) {
		require.Contains(t, s, "// Code generated by torque. DO NOT EDIT.")
	})

	t.Run("has_package_from_component_package_name", func(t *testing.T) {
		require.Contains(t, s, "package mypkg")
	})
}

// TestGenerateFromManifest_struct_and_constructors verifies the generated struct and constructor functions.
func TestGenerateFromManifest_struct_and_constructors(t *testing.T) {
	manifest, tmpDir := makeManifest(t, "<div>hello</div>")
	_, err := pageobjects.GenerateFromManifest(manifest, pageobjects.StaticConfig{Tag: "browser"})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(tmpDir, "foo_browser.gen.go"))
	require.NoError(t, err)
	s := string(content)

	t.Run("has_page_object_struct", func(t *testing.T) {
		require.Contains(t, s, "type FooPageObject struct")
	})

	t.Run("has_page_constructor", func(t *testing.T) {
		require.Contains(t, s, "func NewFooPageObject(page playwright.Page) *FooPageObject")
	})

	t.Run("has_locator_constructor", func(t *testing.T) {
		require.Contains(t, s, "func NewFooPageObjectFromLocator(locator playwright.Locator) *FooPageObject")
	})
}

// TestGenerateFromManifest_leaf_elements verifies that data-test-id attributes in
// the Template HTML produce typed accessor methods.
func TestGenerateFromManifest_leaf_elements(t *testing.T) {
	tmpDir := t.TempDir()
	tmpl := `<div><button data-test-id="submit-btn">Submit</button><input data-test-id="email-field"/></div>`
	manifest := &analysis.ProjectManifest{
		Components: map[string]*analysis.Component{
			"example.Form": {
				TypeName:    "Form",
				PackageName: "mypkg",
				PackagePath: "example",
				SourceFile:  filepath.Join(tmpDir, "form.go"),
				Template:    &tmpl,
			},
		},
	}

	written, err := pageobjects.GenerateFromManifest(manifest, pageobjects.StaticConfig{Tag: "browser"})
	require.NoError(t, err)
	require.Len(t, written, 1)

	content, err := os.ReadFile(written[0])
	require.NoError(t, err)
	s := string(content)

	t.Run("button_tag_yields_button_element_method", func(t *testing.T) {
		require.Contains(t, s, "func (p *FormPageObject) SubmitBtn() *pageobjects.ButtonElement")
	})

	t.Run("input_tag_yields_input_element_method", func(t *testing.T) {
		require.Contains(t, s, "func (p *FormPageObject) EmailField() *pageobjects.InputElement")
	})

	t.Run("locator_uses_data_test_id_selector", func(t *testing.T) {
		require.Contains(t, s, `[data-test-id='submit-btn']`)
		require.Contains(t, s, `[data-test-id='email-field']`)
	})
}

// TestGenerateFromManifest_child_same_package verifies that children in the same
// package produce same-package accessor methods using TemplateName for the selector.
func TestGenerateFromManifest_child_same_package(t *testing.T) {
	tmpDir := t.TempDir()
	btnTmpl := `<button data-test-id="btn">Click</button>`
	cardTmpl := `<div>{{template "card-action" .Action}}</div>`
	manifest := &analysis.ProjectManifest{
		Components: map[string]*analysis.Component{
			"example.Button": {
				TypeName:    "Button",
				PackageName: "mypkg",
				PackagePath: "example",
				SourceFile:  filepath.Join(tmpDir, "button.go"),
				Template:    &btnTmpl,
			},
			"example.Card": {
				TypeName:    "Card",
				PackageName: "mypkg",
				PackagePath: "example",
				SourceFile:  filepath.Join(tmpDir, "card.go"),
				Template:    &cardTmpl,
				Children: []analysis.ComponentRef{
					{FieldName: "Action", TemplateName: "card-action", TypeRef: "example.Button"},
				},
			},
		},
	}

	_, err := pageobjects.GenerateFromManifest(manifest, pageobjects.StaticConfig{Tag: "browser"})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(tmpDir, "card_browser.gen.go"))
	require.NoError(t, err)
	s := string(content)

	t.Run("method_returns_same_package_child_page_object", func(t *testing.T) {
		require.Contains(t, s, "func (p *CardPageObject) Action() *ButtonPageObject")
	})

	t.Run("method_uses_from_locator_constructor", func(t *testing.T) {
		require.Contains(t, s, "NewButtonPageObjectFromLocator(")
	})

	t.Run("selector_uses_template_name_not_field_name", func(t *testing.T) {
		require.Contains(t, s, `[data-test-id='card-action']`)
	})
}

// TestGenerateFromManifest_cross_package_child verifies that children from a different
// package produce qualified return types and trigger a cross-package import.
func TestGenerateFromManifest_cross_package_child(t *testing.T) {
	tmpDir := t.TempDir()
	btnTmpl := `<button>Click</button>`
	cardTmpl := `<div>{{template "card-action" .Action}}</div>`
	manifest := &analysis.ProjectManifest{
		Components: map[string]*analysis.Component{
			"example/buttons.Button": {
				TypeName:    "Button",
				PackageName: "buttons",
				PackagePath: "example/buttons",
				SourceFile:  filepath.Join(tmpDir, "buttons", "button.go"),
				Template:    &btnTmpl,
			},
			"example/cards.Card": {
				TypeName:    "Card",
				PackageName: "cards",
				PackagePath: "example/cards",
				SourceFile:  filepath.Join(tmpDir, "cards", "card.go"),
				Template:    &cardTmpl,
				Children: []analysis.ComponentRef{
					{FieldName: "Action", TemplateName: "card-action", TypeRef: "example/buttons.Button"},
				},
			},
		},
	}

	require.NoError(t, os.MkdirAll(filepath.Join(tmpDir, "buttons"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(tmpDir, "cards"), 0o755))

	_, err := pageobjects.GenerateFromManifest(manifest, pageobjects.StaticConfig{Tag: "browser"})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(tmpDir, "cards", "card_browser.gen.go"))
	require.NoError(t, err)
	s := string(content)

	t.Run("method_returns_qualified_child_page_object", func(t *testing.T) {
		require.Contains(t, s, "func (p *CardPageObject) Action() *buttons.ButtonPageObject")
	})

	t.Run("method_calls_qualified_from_locator_constructor", func(t *testing.T) {
		require.Contains(t, s, "buttons.NewButtonPageObjectFromLocator(")
	})

	t.Run("cross_package_import_is_emitted", func(t *testing.T) {
		require.Contains(t, s, `"example/buttons"`)
	})
}

// TestGenerateFromManifest_multi_component_source_file verifies that two components
// sharing the same SourceFile are both generated into a single output file.
func TestGenerateFromManifest_multi_component_source_file(t *testing.T) {
	tmpDir := t.TempDir()
	sharedSource := filepath.Join(tmpDir, "widgets.go")
	tmplA := `<div>widget a</div>`
	tmplB := `<span>widget b</span>`
	manifest := &analysis.ProjectManifest{
		Components: map[string]*analysis.Component{
			"example.WidgetA": {
				TypeName:    "WidgetA",
				PackageName: "mypkg",
				PackagePath: "example",
				SourceFile:  sharedSource,
				Template:    &tmplA,
			},
			"example.WidgetB": {
				TypeName:    "WidgetB",
				PackageName: "mypkg",
				PackagePath: "example",
				SourceFile:  sharedSource,
				Template:    &tmplB,
			},
		},
	}

	written, err := pageobjects.GenerateFromManifest(manifest, pageobjects.StaticConfig{Tag: "browser"})
	require.NoError(t, err)

	t.Run("only_one_file_written", func(t *testing.T) {
		require.Len(t, written, 1)
		require.Equal(t, filepath.Join(tmpDir, "widgets_browser.gen.go"), written[0])
	})

	content, err := os.ReadFile(filepath.Join(tmpDir, "widgets_browser.gen.go"))
	require.NoError(t, err)
	s := string(content)

	t.Run("contains_widget_a_page_object", func(t *testing.T) {
		require.Contains(t, s, "type WidgetAPageObject struct")
	})

	t.Run("contains_widget_b_page_object", func(t *testing.T) {
		require.Contains(t, s, "type WidgetBPageObject struct")
	})
}

// TestGenerateFromManifest_nil_template verifies that components with nil templates
// are skipped without error, but other components in the same file group still generate.
func TestGenerateFromManifest_nil_template(t *testing.T) {
	t.Run("nil_template_alone_writes_nothing", func(t *testing.T) {
		tmpDir := t.TempDir()
		manifest := &analysis.ProjectManifest{
			Components: map[string]*analysis.Component{
				"example.NoTemplate": {
					TypeName:    "NoTemplate",
					PackageName: "mypkg",
					PackagePath: "example",
					SourceFile:  filepath.Join(tmpDir, "no_template.go"),
					Template:    nil,
				},
			},
		}

		written, err := pageobjects.GenerateFromManifest(manifest, pageobjects.StaticConfig{Tag: "browser"})
		require.NoError(t, err)
		require.Empty(t, written)

		_, statErr := os.Stat(filepath.Join(tmpDir, "no_template_browser.gen.go"))
		require.True(t, os.IsNotExist(statErr))
	})

	t.Run("nil_template_sibling_still_generates", func(t *testing.T) {
		tmpDir := t.TempDir()
		sharedSource := filepath.Join(tmpDir, "mixed.go")
		tmpl := `<div>valid</div>`
		manifest := &analysis.ProjectManifest{
			Components: map[string]*analysis.Component{
				"example.HasTemplate": {
					TypeName:    "HasTemplate",
					PackageName: "mypkg",
					PackagePath: "example",
					SourceFile:  sharedSource,
					Template:    &tmpl,
				},
				"example.NoTemplate": {
					TypeName:    "NoTemplate",
					PackageName: "mypkg",
					PackagePath: "example",
					SourceFile:  sharedSource,
					Template:    nil,
				},
			},
		}

		written, err := pageobjects.GenerateFromManifest(manifest, pageobjects.StaticConfig{Tag: "browser"})
		require.NoError(t, err)
		require.Len(t, written, 1)

		content, err := os.ReadFile(written[0])
		require.NoError(t, err)
		s := string(content)
		require.Contains(t, s, "type HasTemplatePageObject struct")
		require.NotContains(t, s, "type NoTemplatePageObject struct")
	})
}

// TestGenerateFromManifest_build_tag verifies build tag emission rules.
func TestGenerateFromManifest_build_tag(t *testing.T) {
	t.Run("default_tag_browser", func(t *testing.T) {
		manifest, tmpDir := makeManifest(t, "<div>hello</div>")
		_, err := pageobjects.GenerateFromManifest(manifest, pageobjects.StaticConfig{Tag: "browser"})
		require.NoError(t, err)
		content, err := os.ReadFile(filepath.Join(tmpDir, "foo_browser.gen.go"))
		require.NoError(t, err)
		require.Contains(t, string(content), "//go:build browser")
	})

	t.Run("custom_tag_e2e", func(t *testing.T) {
		manifest, tmpDir := makeManifest(t, "<div>hello</div>")
		_, err := pageobjects.GenerateFromManifest(manifest, pageobjects.StaticConfig{Tag: "e2e"})
		require.NoError(t, err)
		content, err := os.ReadFile(filepath.Join(tmpDir, "foo_browser.gen.go"))
		require.NoError(t, err)
		require.Contains(t, string(content), "//go:build e2e")
	})

	t.Run("empty_tag_no_build_constraint", func(t *testing.T) {
		manifest, tmpDir := makeManifest(t, "<div>hello</div>")
		_, err := pageobjects.GenerateFromManifest(manifest, pageobjects.StaticConfig{Tag: ""})
		require.NoError(t, err)
		content, err := os.ReadFile(filepath.Join(tmpDir, "foo_browser.gen.go"))
		require.NoError(t, err)
		require.NotContains(t, string(content), "//go:build")
	})
}
