//go:build browser

// Code generated by generate-controllers. DO NOT EDIT.

package pageobjects

import (
	playwright "github.com/mxschmitt/playwright-go"
)

type DocsLayoutController struct {
	locator playwright.Locator
}

func NewDocsLayoutController(page playwright.Page) *DocsLayoutController {
	return &DocsLayoutController{locator: page.Locator("html")}
}

func NewDocsLayoutControllerFromLocator(locator playwright.Locator) *DocsLayoutController {
	return &DocsLayoutController{locator: locator}
}

func (c *DocsLayoutController) Search() *SearchDialogController {
	return NewSearchDialogControllerFromLocator(c.locator.Locator("[data-test-id='search-dialog']"))
}
