//go:build browser

// Code generated by generate-controllers. DO NOT EDIT.

package pageobjects

import (
	playwright "github.com/mxschmitt/playwright-go"
)

type DocumentController struct {
	locator playwright.Locator
}

func NewDocumentController(page playwright.Page) *DocumentController {
	return &DocumentController{locator: page.Locator("html")}
}

func NewDocumentControllerFromLocator(locator playwright.Locator) *DocumentController {
	return &DocumentController{locator: locator}
}
