//go:build browser

// Code generated by generate-controllers. DO NOT EDIT.

package pageobjects

import (
	playwright "github.com/mxschmitt/playwright-go"
)

type SearchDialogController struct {
	locator playwright.Locator
}

func NewSearchDialogController(page playwright.Page) *SearchDialogController {
	return &SearchDialogController{locator: page.Locator("html")}
}

func NewSearchDialogControllerFromLocator(locator playwright.Locator) *SearchDialogController {
	return &SearchDialogController{locator: locator}
}
