//go:build browser

// Code generated by generate-controllers. DO NOT EDIT.

package pageobjects

import (
	playwright "github.com/mxschmitt/playwright-go"
	"github.com/tylermmorton/torque/pkg/pageobjects"
)

type StargazersController struct {
	locator playwright.Locator
}

func NewStargazersController(page playwright.Page) *StargazersController {
	return &StargazersController{locator: page.Locator("html")}
}

func NewStargazersControllerFromLocator(locator playwright.Locator) *StargazersController {
	return &StargazersController{locator: locator}
}

func (c *StargazersController) StarsContainer() *pageobjects.Element {
	return pageobjects.NewElement(c.locator.Locator("[data-test-id='stars-container']"))
}

func (c *StargazersController) StarCount() *pageobjects.Element {
	return pageobjects.NewElement(c.locator.Locator("[data-test-id='star-count']"))
}
