root = "."
testdata_dir = "testdata"
tmp_dir = ".build"

[build]
  args_bin = []
  bin = "./.build/app"
  cmd = "npm run build:js && npm run build:css && npm run build:go"
  delay = 250
  exclude_dir = ["node_modules", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go", ".gen.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = [
    "go", "env",
    "md",
    "js", "ts", "html",
  ]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 1000
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
